### ISSUE TITLE
How do you run migrations for different tenants after you moved dbase names to the landlord.tenant.database?

### ISSUE THREAD

**Issue by yarooze** [SiMoeBoe/multi-tenancy-yon-talk#1]
@SiMoeBoe  Great work! Nice solutions and explanations. I like it very much.

However one question: How do you run migrations for different tenants after you moved dbase names to the landlord.tenant.database?  There is no RequestEvent in the migration commands, so TenantResolver does nothing. 

...and isn't "database" a reserved word? :)

**Comment by SiMoeBoe** [comment]
Hello @yarooze,

sorry for my late answer, I was on vacation :-)
Thank you very much for your compliments!

Regarding your questions:
You're right, there is no RequestEvent, but a `ConsoleCommandEvent`.
In the function `App\Tenant\TenantResolver::setTenantByCLI()` I used this event to add a --tenant option to each Symfony Command, for the migration as well.

Now, you can exec something like `docker compose exec php bin/console doctrine:migrations:migrate --configuration=migrations/tenant.php --tenant=tenant1.localhost` to run a migration explicitly for one specific tenant.

Of course you have to run this command multiple times (one per tenant), but it should be no problem to automate this with an extra command or a bash script.

Concerning your question if database is a reserved word: Yes for many SQL databases, but not for [PostGres](https://www.postgresql.org/docs/current/sql-keywords-appendix.html) that I used in this project :-)  

Hope my answers helps you!

Best regards,
Simon
